disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "RJLTuquero"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  favicon = "favicon.ico"
  logo = "img/apple-touch-icon.png"
  #secondaryLogo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
   name = "Richelle Jade L. Tuquero"
   email = "richellejade.l.tuquero@gmail.com"
   image = "IMG_3950.jpg"
   imageQuality = 96
   headline = "PhD student in Theoretical Physics "
   bio = "Trying my best"
   links = [
     { email = "mailto:richellejade.l.tuquero@gmail.com" },
     { github = "https://github.com/richellejadeT" },
     { google = "https://scholar.google.com/citations?user=AEqTTAwAAAAJ&hl=en" },
     { orcid = "https://orcid.org/0000-0001-7928-9529" },
     { researchgate = "https://www.researchgate.net/profile/Richelle-Jade-Tuquero" }
  ]

